apiVersion: extensions/cloudheads1
kind: Deployment
metadata:
  name: pod-cloudheads1
  labels:
    commit: ${GIT_COMMIT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-cloudheads1
  template:
    metadata:
      labels:
        app: cloudheads1
        commit: ${GIT_COMMIT}
        color: blue
    spec:
      containers:
      - name: cloudheads1
        image: iad.ocir.io/codeatcustomer1/cloudheads/cloudheads1:${GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - name: cloudheads1
          containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: podinfo
            mountPath: /tmp
            readOnly: false
      volumes:
        - name: podinfo
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels 
      imagePullSecrets:
        - name: cloud1secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloudheads1
  labels:
    app: cloudheads1
    commit: ${GIT_COMMIT}
spec:
  ports:
  - port: 30000
    targetPort: 8080
  selector:
    app: cloudheads1
    color: blue
  type: ClusterIP
---
