spring:
  datasource: 
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    platform: h2
    ddl-auto: none
management:
  security:
    enabled: false
